import os
import json
from datetime import datetime

OUTPUT_DIR = "reports"

def ensure_output_dir():
    if not os.path.exists(OUTPUT_DIR):
        os.makedirs(OUTPUT_DIR)

def generate_markdown_report(finding):
    title = finding.get("title", "Untitled Finding")
    program = finding.get("program", "Unknown Program")
    target = finding.get("target", "Unknown Target")
    severity = finding.get("severity", "Unrated")
    description = finding.get("description", "No description provided.")
    reproduction = finding.get("reproduction_steps", "No reproduction steps provided.")
    impact = finding.get("impact", "No impact provided.")
    fingerprint = finding.get("fingerprint", "no-fingerprint")
    money_score = finding.get("money_score", 0)

    md = f"""# {title}

**Program:** {program}  
**Target:** {target}  
**Severity:** {severity}  
**Money Score:** {money_score}  
**Fingerprint:** `{fingerprint}`  
**Generated:** {datetime.utcnow().isoformat()} UTC

---

## Summary
{description}

---

## Steps to Reproduce
{reproduction}

---

## Impact
{impact}

---

## Notes
This report was automatically generated by your analysis engine and filtered for:
- high payout potential  
- high acceptance probability  
- non-duplicate status  
- fully automatable vulnerability class  

Submit manually for maximum control and payout confidence.
"""

    return md

def write_report_file(finding):
    ensure_output_dir()
    fingerprint = finding.get("fingerprint", "no-fingerprint")
    safe_name = fingerprint.replace("|", "_").replace("/", "_")
    filename = f"{OUTPUT_DIR}/{safe_name}.md"

    with open(filename, "w", encoding="utf-8") as f:
        f.write(generate_markdown_report(finding))

    print(f"[report_generator] Wrote report: {filename}")

def generate_reports(findings):
    print(f"[report_generator] Generating {len(findings)} payout-ready reports...")
    for f in findings:
        write_report_file(f)
    print("[report_generator] Report generation complete.")
