// Auto-generated by scripts/generate_data.py — do not edit manually
// This is a SAMPLE file. Real data is generated by GitHub Actions.
const SF_DATA = {
  "generated": "2026-05-08",
  "programs": [
    {
      "id": "example-1",
      "name": "Example Corp",
      "platform": "HackerOne",
      "scope": ["https://example.com", "https://api.example.com"],
      "active": true,
      "added": "2026-05-08",
      "notes": "Main web app + API"
    }
  ],
  "all_findings": [
    {
      "title": "Missing Strict-Transport-Security (HSTS)",
      "description": "Without HSTS, browsers can be tricked into downgrading HTTPS connections.",
      "severity": "medium",
      "evidence": "Header 'strict-transport-security' not present in response from https://example.com",
      "remediation": "Add: Strict-Transport-Security: max-age=31536000; includeSubDomains; preload",
      "target": "https://example.com",
      "program_id": "example-1",
      "timestamp": "2026-05-08T06:12:00Z"
    },
    {
      "title": "Missing Content-Security-Policy (CSP)",
      "description": "No CSP means arbitrary scripts can execute, greatly increasing XSS risk.",
      "severity": "medium",
      "evidence": "Header 'content-security-policy' not present in response from https://example.com",
      "remediation": "Define a strict Content-Security-Policy for your application.",
      "target": "https://example.com",
      "program_id": "example-1",
      "timestamp": "2026-05-08T06:12:01Z"
    },
    {
      "title": "Server version disclosure",
      "description": "The Server header reveals software/version info, helping attackers target CVEs.",
      "severity": "low",
      "evidence": "Server: nginx/1.18.0",
      "remediation": "Remove or genericise the Server header in your web server config.",
      "target": "https://example.com",
      "program_id": "example-1",
      "timestamp": "2026-05-08T06:12:02Z"
    },
    {
      "title": "Missing X-Frame-Options",
      "description": "Pages can be embedded in iframes, enabling clickjacking attacks.",
      "severity": "medium",
      "evidence": "Header 'x-frame-options' not present in response from https://example.com",
      "remediation": "Add: X-Frame-Options: DENY (or use CSP frame-ancestors)",
      "target": "https://api.example.com",
      "program_id": "example-1",
      "timestamp": "2026-05-08T06:13:00Z"
    },
    {
      "title": "Cookie missing HttpOnly flag",
      "description": "Cookie 'session' is accessible via JavaScript, enabling theft via XSS.",
      "severity": "medium",
      "evidence": "Set-Cookie: session=abc123; Path=/",
      "remediation": "Add the HttpOnly attribute to all session/auth cookies.",
      "target": "https://api.example.com",
      "program_id": "example-1",
      "timestamp": "2026-05-08T06:13:05Z"
    }
  ],
  "time_series": [
    {"date":"2026-04-09","critical":0,"high":0,"medium":0,"low":0,"info":0,"total":0},
    {"date":"2026-04-10","critical":0,"high":0,"medium":0,"low":0,"info":0,"total":0},
    {"date":"2026-04-11","critical":0,"high":0,"medium":0,"low":0,"info":0,"total":0},
    {"date":"2026-04-12","critical":0,"high":0,"medium":0,"low":0,"info":0,"total":0},
    {"date":"2026-04-13","critical":0,"high":0,"medium":0,"low":0,"info":0,"total":0},
    {"date":"2026-04-14","critical":0,"high":0,"medium":0,"low":0,"info":0,"total":0},
    {"date":"2026-04-15","critical":0,"high":0,"medium":0,"low":0,"info":0,"total":0},
    {"date":"2026-04-16","critical":0,"high":0,"medium":0,"low":0,"info":0,"total":0},
    {"date":"2026-04-17","critical":0,"high":0,"medium":0,"low":0,"info":0,"total":0},
    {"date":"2026-04-18","critical":0,"high":0,"medium":0,"low":0,"info":0,"total":0},
    {"date":"2026-04-19","critical":0,"high":0,"medium":0,"low":0,"info":0,"total":0},
    {"date":"2026-04-20","critical":0,"high":0,"medium":0,"low":0,"info":0,"total":0},
    {"date":"2026-04-21","critical":0,"high":0,"medium":0,"low":0,"info":0,"total":0},
    {"date":"2026-04-22","critical":0,"high":0,"medium":0,"low":0,"info":0,"total":0},
    {"date":"2026-04-23","critical":0,"high":0,"medium":0,"low":0,"info":0,"total":0},
    {"date":"2026-04-24","critical":0,"high":0,"medium":0,"low":0,"info":0,"total":0},
    {"date":"2026-04-25","critical":0,"high":0,"medium":0,"low":0,"info":0,"total":0},
    {"date":"2026-04-26","critical":0,"high":0,"medium":0,"low":0,"info":0,"total":0},
    {"date":"2026-04-27","critical":0,"high":0,"medium":0,"low":0,"info":0,"total":0},
    {"date":"2026-04-28","critical":0,"high":0,"medium":0,"low":0,"info":0,"total":0},
    {"date":"2026-04-29","critical":0,"high":0,"medium":0,"low":0,"info":0,"total":0},
    {"date":"2026-04-30","critical":0,"high":0,"medium":0,"low":0,"info":0,"total":0},
    {"date":"2026-05-01","critical":0,"high":0,"medium":0,"low":0,"info":0,"total":0},
    {"date":"2026-05-02","critical":0,"high":0,"medium":0,"low":0,"info":0,"total":0},
    {"date":"2026-05-03","critical":0,"high":0,"medium":0,"low":0,"info":0,"total":0},
    {"date":"2026-05-04","critical":0,"high":0,"medium":0,"low":0,"info":0,"total":0},
    {"date":"2026-05-05","critical":0,"high":0,"medium":0,"low":0,"info":0,"total":0},
    {"date":"2026-05-06","critical":0,"high":0,"medium":0,"low":0,"info":0,"total":0},
    {"date":"2026-05-07","critical":0,"high":0,"medium":0,"low":0,"info":0,"total":0},
    {"date":"2026-05-08","critical":0,"high":0,"medium":3,"low":1,"info":0,"total":5}
  ],
  "sev_totals": {"critical": 0, "high": 0, "medium": 3, "low": 1, "info": 0},
  "prog_stats": [
    {"program_id":"example-1","name":"Example Corp","total":5,"critical":0,"high":0,"medium":3,"low":1,"info":0}
  ],
  "total_scans": 1,
  "last_scan": "2026-05-08"
};
