#!/usr/bin/env python3
"""
Merges all daily findings JSON files + programs.json into dashboard/data.js
so the static dashboard works fully offline (file://).
"""
import json
import sys
from pathlib import Path
from datetime import date, timedelta

ROOT = Path(__file__).parent.parent
FINDINGS_DIR = ROOT / "data" / "findings"
PROGRAMS_FILE = ROOT / "programs.json"
OUT_FILE = ROOT / "dashboard" / "data.js"


def main():
    # Load programs
    programs = []
    if PROGRAMS_FILE.exists():
        programs = json.loads(PROGRAMS_FILE.read_text())

    # Load all findings, sorted by date descending
    all_daily = []
    if FINDINGS_DIR.exists():
        for f in sorted(FINDINGS_DIR.glob("*.json"), reverse=True):
            try:
                day = json.loads(f.read_text())
                all_daily.append(day)
            except Exception as e:
                print(f"  WARNING: could not parse {f}: {e}", file=sys.stderr)

    # Flatten all findings, most recent first
    all_findings = []
    for day in all_daily:
        all_findings.extend(day.get("findings", []))

    # Build time-series: findings per day for last 30 days
    today = date.today()
    daily_counts: dict[str, dict] = {}
    for i in range(30):
        d = (today - timedelta(days=29 - i)).isoformat()
        daily_counts[d] = {"date": d, "critical": 0, "high": 0,
                           "medium": 0, "low": 0, "info": 0, "total": 0}

    for day in all_daily:
        d = day.get("date", "")
        if d in daily_counts:
            for f in day.get("findings", []):
                sev = f.get("severity", "info")
                daily_counts[d][sev] = daily_counts[d].get(sev, 0) + 1
                daily_counts[d]["total"] += 1

    time_series = list(daily_counts.values())

    # Severity totals
    sev_totals = {"critical": 0, "high": 0, "medium": 0, "low": 0, "info": 0}
    for f in all_findings:
        sev = f.get("severity", "info")
        sev_totals[sev] = sev_totals.get(sev, 0) + 1

    # Per-program summary
    prog_map = {p["id"]: p for p in programs}
    prog_stats: dict[str, dict] = {}
    for f in all_findings:
        pid = f.get("program_id", "unknown")
        if pid not in prog_stats:
            prog_stats[pid] = {"program_id": pid,
                               "name": prog_map.get(pid, {}).get("name", pid),
                               "total": 0, "critical": 0, "high": 0,
                               "medium": 0, "low": 0, "info": 0}
        prog_stats[pid]["total"] += 1
        sev = f.get("severity", "info")
        prog_stats[pid][sev] += 1

    data = {
        "generated": date.today().isoformat(),
        "programs": programs,
        "all_findings": all_findings,
        "time_series": time_series,
        "sev_totals": sev_totals,
        "prog_stats": list(prog_stats.values()),
        "total_scans": len(all_daily),
        "last_scan": all_daily[0].get("date") if all_daily else None,
    }

    js = "// Auto-generated by scripts/generate_data.py — do not edit manually\n"
    js += "const SF_DATA = " + json.dumps(data, indent=2) + ";\n"

    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text(js)
    print(f"✓ Generated dashboard/data.js — {len(all_findings)} total findings")


if __name__ == "__main__":
    main()
